name: donwload Orfeo Tool Box
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
    
jobs:
  donwload:
    runs-on: windows-latest
    steps:
      - run: mkdir OTB-9.1.1-Win64
      - name: download OTB-9.1.1-Win64.zip
        uses: gamedev-thingy/Download-Extract@done
        with:
          url: https://www.orfeo-toolbox.org/packages/OTB-9.1.1-Win64.zip
          destination: OTB-9.1.10-Win64
          ZIPname: OTB-9.1.1-Win64
      
      - run: 7z a -tzip OTB-9.1.1-Win64.zip OTB-9.1.1-Win64/*
      
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          # Artifact name
          name: OTB-9.1.1-Win64
          # A file, directory or wildcard pattern that describes what to upload
          path: "OTB-9.1.1-Win64.zip"
